// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionsButtonComponentController from "./actions_button_component_controller"
application.register("actions-button-component", ActionsButtonComponentController)

import AvatarComponentController from "./avatar_component_controller"
application.register("avatar-component", AvatarComponentController)

import CopyLinkModalController from "./copy_link_modal_controller"
application.register("copy-link-modal", CopyLinkModalController)

import CustomCheckboxController from "./custom_checkbox_controller"
application.register("custom-checkbox", CustomCheckboxController)

import FieldCheckboxController from "./field_checkbox_controller"
application.register("field-checkbox", FieldCheckboxController)

import FormHeaderController from "./form_header_controller"
application.register("form-header", FormHeaderController)

import FormShowController from "./form_show_controller"
application.register("form-show", FormShowController)

import GlightboxController from "./glightbox_controller"
application.register("glightbox", GlightboxController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PeriodicitySelectorController from "./periodicity_selector_controller"
application.register("periodicity-selector", PeriodicitySelectorController)

import ProfilesFormController from "./profiles_form_controller"
application.register("profiles-form", ProfilesFormController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SkillsController from "./skills_controller"
application.register("skills", SkillsController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)

import SlimMultipleController from "./slim_multiple_controller"
application.register("slim-multiple", SlimMultipleController)

import UploadFileComponentController from "./upload_file_component_controller"
application.register("upload-file-component", UploadFileComponentController)
